services:

  db:
    image: postgres:18.4-alpine3.23
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    volumes:
      - leftovers-database-volume:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - leftovers-network

  test_db:
    image: postgres:18.4-alpine3.23
    restart: always
    shm_size: 128mb
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - leftovers-network

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - leftovers-network

volumes:
  leftovers-database-volume:

networks:
  leftovers-network:
    driver: bridge
